//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8669
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBSet {
    
    private GBSeq[] gBSeqField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBSeq")]
    public GBSeq[] GBSeq {
        get {
            return this.gBSeqField;
        }
        set {
            this.gBSeqField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBSeq {
    
    private string gBSeq_locusField;
    
    private int gBSeq_lengthField;
    
    private string gBSeq_strandednessField;
    
    private string gBSeq_moltypeField;
    
    private string gBSeq_topologyField;
    
    private string gBSeq_divisionField;
    
    private string gBSeq_updatedateField;
    
    private string gBSeq_createdateField;
    
    private string gBSeq_updatereleaseField;
    
    private string gBSeq_createreleaseField;
    
    private string gBSeq_definitionField;
    
    private string gBSeq_primaryaccessionField;
    
    private string gBSeq_entryversionField;
    
    private string gBSeq_accessionversionField;
    
    private string[] gBSeq_otherseqidsField;
    
    private string[] gBSeq_secondaryaccessionsField;
    
    private string gBSeq_projectField;
    
    private string[] gBSeq_keywordsField;
    
    private string gBSeq_segmentField;
    
    private string gBSeq_sourceField;
    
    private string gBSeq_organismField;
    
    private string gBSeq_taxonomyField;
    
    private GBReference[] gBSeq_referencesField;
    
    private string gBSeq_commentField;
    
    private GBComment[] gBSeq_commentsetField;
    
    private GBStrucComment[] gBSeq_struccommentsField;
    
    private string gBSeq_primaryField;
    
    private string gBSeq_sourcedbField;
    
    private string gBSeq_databasereferenceField;
    
    private GBFeature[] gBSeq_featuretableField;
    
    private GBFeatureSet[] gBSeq_featuresetField;
    
    private string gBSeq_sequenceField;
    
    private string gBSeq_contigField;
    
    private GBAltSeqData[] gBSeq_altseqField;
    
    private GBXref[] gBSeq_xrefsField;
    
    /// <remarks/>
    public string GBSeq_locus {
        get {
            return this.gBSeq_locusField;
        }
        set {
            this.gBSeq_locusField = value;
        }
    }
    
    /// <remarks/>
    public int GBSeq_length {
        get {
            return this.gBSeq_lengthField;
        }
        set {
            this.gBSeq_lengthField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_strandedness {
        get {
            return this.gBSeq_strandednessField;
        }
        set {
            this.gBSeq_strandednessField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_moltype {
        get {
            return this.gBSeq_moltypeField;
        }
        set {
            this.gBSeq_moltypeField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_topology {
        get {
            return this.gBSeq_topologyField;
        }
        set {
            this.gBSeq_topologyField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_division {
        get {
            return this.gBSeq_divisionField;
        }
        set {
            this.gBSeq_divisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBSeq_update-date")]
    public string GBSeq_updatedate {
        get {
            return this.gBSeq_updatedateField;
        }
        set {
            this.gBSeq_updatedateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBSeq_create-date")]
    public string GBSeq_createdate {
        get {
            return this.gBSeq_createdateField;
        }
        set {
            this.gBSeq_createdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBSeq_update-release")]
    public string GBSeq_updaterelease {
        get {
            return this.gBSeq_updatereleaseField;
        }
        set {
            this.gBSeq_updatereleaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBSeq_create-release")]
    public string GBSeq_createrelease {
        get {
            return this.gBSeq_createreleaseField;
        }
        set {
            this.gBSeq_createreleaseField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_definition {
        get {
            return this.gBSeq_definitionField;
        }
        set {
            this.gBSeq_definitionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBSeq_primary-accession")]
    public string GBSeq_primaryaccession {
        get {
            return this.gBSeq_primaryaccessionField;
        }
        set {
            this.gBSeq_primaryaccessionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBSeq_entry-version")]
    public string GBSeq_entryversion {
        get {
            return this.gBSeq_entryversionField;
        }
        set {
            this.gBSeq_entryversionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBSeq_accession-version")]
    public string GBSeq_accessionversion {
        get {
            return this.gBSeq_accessionversionField;
        }
        set {
            this.gBSeq_accessionversionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("GBSeq_other-seqids")]
    [System.Xml.Serialization.XmlArrayItemAttribute("GBSeqid", IsNullable=false)]
    public string[] GBSeq_otherseqids {
        get {
            return this.gBSeq_otherseqidsField;
        }
        set {
            this.gBSeq_otherseqidsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("GBSeq_secondary-accessions")]
    [System.Xml.Serialization.XmlArrayItemAttribute("GBSecondary-accn", IsNullable=false)]
    public string[] GBSeq_secondaryaccessions {
        get {
            return this.gBSeq_secondaryaccessionsField;
        }
        set {
            this.gBSeq_secondaryaccessionsField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_project {
        get {
            return this.gBSeq_projectField;
        }
        set {
            this.gBSeq_projectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("GBKeyword", IsNullable=false)]
    public string[] GBSeq_keywords {
        get {
            return this.gBSeq_keywordsField;
        }
        set {
            this.gBSeq_keywordsField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_segment {
        get {
            return this.gBSeq_segmentField;
        }
        set {
            this.gBSeq_segmentField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_source {
        get {
            return this.gBSeq_sourceField;
        }
        set {
            this.gBSeq_sourceField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_organism {
        get {
            return this.gBSeq_organismField;
        }
        set {
            this.gBSeq_organismField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_taxonomy {
        get {
            return this.gBSeq_taxonomyField;
        }
        set {
            this.gBSeq_taxonomyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("GBReference", IsNullable=false)]
    public GBReference[] GBSeq_references {
        get {
            return this.gBSeq_referencesField;
        }
        set {
            this.gBSeq_referencesField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_comment {
        get {
            return this.gBSeq_commentField;
        }
        set {
            this.gBSeq_commentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("GBSeq_comment-set")]
    [System.Xml.Serialization.XmlArrayItemAttribute("GBComment", IsNullable=false)]
    public GBComment[] GBSeq_commentset {
        get {
            return this.gBSeq_commentsetField;
        }
        set {
            this.gBSeq_commentsetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("GBSeq_struc-comments")]
    [System.Xml.Serialization.XmlArrayItemAttribute("GBStrucComment", IsNullable=false)]
    public GBStrucComment[] GBSeq_struccomments {
        get {
            return this.gBSeq_struccommentsField;
        }
        set {
            this.gBSeq_struccommentsField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_primary {
        get {
            return this.gBSeq_primaryField;
        }
        set {
            this.gBSeq_primaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBSeq_source-db")]
    public string GBSeq_sourcedb {
        get {
            return this.gBSeq_sourcedbField;
        }
        set {
            this.gBSeq_sourcedbField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBSeq_database-reference")]
    public string GBSeq_databasereference {
        get {
            return this.gBSeq_databasereferenceField;
        }
        set {
            this.gBSeq_databasereferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("GBSeq_feature-table")]
    [System.Xml.Serialization.XmlArrayItemAttribute("GBFeature", IsNullable=false)]
    public GBFeature[] GBSeq_featuretable {
        get {
            return this.gBSeq_featuretableField;
        }
        set {
            this.gBSeq_featuretableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("GBSeq_feature-set")]
    [System.Xml.Serialization.XmlArrayItemAttribute("GBFeatureSet", IsNullable=false)]
    public GBFeatureSet[] GBSeq_featureset {
        get {
            return this.gBSeq_featuresetField;
        }
        set {
            this.gBSeq_featuresetField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_sequence {
        get {
            return this.gBSeq_sequenceField;
        }
        set {
            this.gBSeq_sequenceField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_contig {
        get {
            return this.gBSeq_contigField;
        }
        set {
            this.gBSeq_contigField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("GBSeq_alt-seq")]
    [System.Xml.Serialization.XmlArrayItemAttribute("GBAltSeqData", IsNullable=false)]
    public GBAltSeqData[] GBSeq_altseq {
        get {
            return this.gBSeq_altseqField;
        }
        set {
            this.gBSeq_altseqField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("GBXref", IsNullable=false)]
    public GBXref[] GBSeq_xrefs {
        get {
            return this.gBSeq_xrefsField;
        }
        set {
            this.gBSeq_xrefsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBReference {
    
    private string gBReference_referenceField;
    
    private string gBReference_positionField;
    
    private string[] gBReference_authorsField;
    
    private string gBReference_consortiumField;
    
    private string gBReference_titleField;
    
    private string gBReference_journalField;
    
    private GBXref[] gBReference_xrefField;
    
    private string gBReference_pubmedField;
    
    private string gBReference_remarkField;
    
    /// <remarks/>
    public string GBReference_reference {
        get {
            return this.gBReference_referenceField;
        }
        set {
            this.gBReference_referenceField = value;
        }
    }
    
    /// <remarks/>
    public string GBReference_position {
        get {
            return this.gBReference_positionField;
        }
        set {
            this.gBReference_positionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("GBAuthor", IsNullable=false)]
    public string[] GBReference_authors {
        get {
            return this.gBReference_authorsField;
        }
        set {
            this.gBReference_authorsField = value;
        }
    }
    
    /// <remarks/>
    public string GBReference_consortium {
        get {
            return this.gBReference_consortiumField;
        }
        set {
            this.gBReference_consortiumField = value;
        }
    }
    
    /// <remarks/>
    public string GBReference_title {
        get {
            return this.gBReference_titleField;
        }
        set {
            this.gBReference_titleField = value;
        }
    }
    
    /// <remarks/>
    public string GBReference_journal {
        get {
            return this.gBReference_journalField;
        }
        set {
            this.gBReference_journalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("GBXref", IsNullable=false)]
    public GBXref[] GBReference_xref {
        get {
            return this.gBReference_xrefField;
        }
        set {
            this.gBReference_xrefField = value;
        }
    }
    
    /// <remarks/>
    public string GBReference_pubmed {
        get {
            return this.gBReference_pubmedField;
        }
        set {
            this.gBReference_pubmedField = value;
        }
    }
    
    /// <remarks/>
    public string GBReference_remark {
        get {
            return this.gBReference_remarkField;
        }
        set {
            this.gBReference_remarkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBXref {
    
    private string gBXref_dbnameField;
    
    private string gBXref_idField;
    
    /// <remarks/>
    public string GBXref_dbname {
        get {
            return this.gBXref_dbnameField;
        }
        set {
            this.gBXref_dbnameField = value;
        }
    }
    
    /// <remarks/>
    public string GBXref_id {
        get {
            return this.gBXref_idField;
        }
        set {
            this.gBXref_idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBComment {
    
    private string gBComment_typeField;
    
    private string[] gBComment_paragraphsField;
    
    /// <remarks/>
    public string GBComment_type {
        get {
            return this.gBComment_typeField;
        }
        set {
            this.gBComment_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("GBCommentParagraph", IsNullable=false)]
    public string[] GBComment_paragraphs {
        get {
            return this.gBComment_paragraphsField;
        }
        set {
            this.gBComment_paragraphsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBStrucComment {
    
    private string gBStrucComment_nameField;
    
    private GBStrucCommentItem[] gBStrucComment_itemsField;
    
    /// <remarks/>
    public string GBStrucComment_name {
        get {
            return this.gBStrucComment_nameField;
        }
        set {
            this.gBStrucComment_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("GBStrucCommentItem", IsNullable=false)]
    public GBStrucCommentItem[] GBStrucComment_items {
        get {
            return this.gBStrucComment_itemsField;
        }
        set {
            this.gBStrucComment_itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBStrucCommentItem {
    
    private string gBStrucCommentItem_tagField;
    
    private string gBStrucCommentItem_valueField;
    
    private string gBStrucCommentItem_urlField;
    
    /// <remarks/>
    public string GBStrucCommentItem_tag {
        get {
            return this.gBStrucCommentItem_tagField;
        }
        set {
            this.gBStrucCommentItem_tagField = value;
        }
    }
    
    /// <remarks/>
    public string GBStrucCommentItem_value {
        get {
            return this.gBStrucCommentItem_valueField;
        }
        set {
            this.gBStrucCommentItem_valueField = value;
        }
    }
    
    /// <remarks/>
    public string GBStrucCommentItem_url {
        get {
            return this.gBStrucCommentItem_urlField;
        }
        set {
            this.gBStrucCommentItem_urlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBFeature {
    
    private string gBFeature_keyField;
    
    private string gBFeature_locationField;
    
    private GBInterval[] gBFeature_intervalsField;
    
    private string gBFeature_operatorField;
    
    private GBFeature_partial5 gBFeature_partial5Field;
    
    private GBFeature_partial3 gBFeature_partial3Field;
    
    private GBQualifier[] gBFeature_qualsField;
    
    private GBXref[] gBFeature_xrefsField;
    
    /// <remarks/>
    public string GBFeature_key {
        get {
            return this.gBFeature_keyField;
        }
        set {
            this.gBFeature_keyField = value;
        }
    }
    
    /// <remarks/>
    public string GBFeature_location {
        get {
            return this.gBFeature_locationField;
        }
        set {
            this.gBFeature_locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("GBInterval", IsNullable=false)]
    public GBInterval[] GBFeature_intervals {
        get {
            return this.gBFeature_intervalsField;
        }
        set {
            this.gBFeature_intervalsField = value;
        }
    }
    
    /// <remarks/>
    public string GBFeature_operator {
        get {
            return this.gBFeature_operatorField;
        }
        set {
            this.gBFeature_operatorField = value;
        }
    }
    
    /// <remarks/>
    public GBFeature_partial5 GBFeature_partial5 {
        get {
            return this.gBFeature_partial5Field;
        }
        set {
            this.gBFeature_partial5Field = value;
        }
    }
    
    /// <remarks/>
    public GBFeature_partial3 GBFeature_partial3 {
        get {
            return this.gBFeature_partial3Field;
        }
        set {
            this.gBFeature_partial3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("GBQualifier", IsNullable=false)]
    public GBQualifier[] GBFeature_quals {
        get {
            return this.gBFeature_qualsField;
        }
        set {
            this.gBFeature_qualsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("GBXref", IsNullable=false)]
    public GBXref[] GBFeature_xrefs {
        get {
            return this.gBFeature_xrefsField;
        }
        set {
            this.gBFeature_xrefsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBInterval {
    
    private int gBInterval_fromField;
    
    private int gBInterval_toField;
    
    private int gBInterval_pointField;
    
    private GBInterval_iscomp gBInterval_iscompField;
    
    private GBInterval_interbp gBInterval_interbpField;
    
    private string gBInterval_accessionField;
    
    /// <remarks/>
    public int GBInterval_from {
        get {
            return this.gBInterval_fromField;
        }
        set {
            this.gBInterval_fromField = value;
        }
    }
    
    /// <remarks/>
    public int GBInterval_to {
        get {
            return this.gBInterval_toField;
        }
        set {
            this.gBInterval_toField = value;
        }
    }
    
    /// <remarks/>
    public int GBInterval_point {
        get {
            return this.gBInterval_pointField;
        }
        set {
            this.gBInterval_pointField = value;
        }
    }
    
    /// <remarks/>
    public GBInterval_iscomp GBInterval_iscomp {
        get {
            return this.gBInterval_iscompField;
        }
        set {
            this.gBInterval_iscompField = value;
        }
    }
    
    /// <remarks/>
    public GBInterval_interbp GBInterval_interbp {
        get {
            return this.gBInterval_interbpField;
        }
        set {
            this.gBInterval_interbpField = value;
        }
    }
    
    /// <remarks/>
    public string GBInterval_accession {
        get {
            return this.gBInterval_accessionField;
        }
        set {
            this.gBInterval_accessionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBInterval_iscomp {
    
    private GBInterval_iscompValue valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public GBInterval_iscompValue value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
public enum GBInterval_iscompValue {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBInterval_interbp {
    
    private GBInterval_interbpValue valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public GBInterval_interbpValue value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
public enum GBInterval_interbpValue {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBFeature_partial5 {
    
    private GBFeature_partial5Value valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public GBFeature_partial5Value value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
public enum GBFeature_partial5Value {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBFeature_partial3 {
    
    private GBFeature_partial3Value valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public GBFeature_partial3Value value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
public enum GBFeature_partial3Value {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBQualifier {
    
    private string gBQualifier_nameField;
    
    private string gBQualifier_valueField;
    
    /// <remarks/>
    public string GBQualifier_name {
        get {
            return this.gBQualifier_nameField;
        }
        set {
            this.gBQualifier_nameField = value;
        }
    }
    
    /// <remarks/>
    public string GBQualifier_value {
        get {
            return this.gBQualifier_valueField;
        }
        set {
            this.gBQualifier_valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBFeatureSet {
    
    private string gBFeatureSet_annotsourceField;
    
    private GBFeature[] gBFeatureSet_featuresField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBFeatureSet_annot-source")]
    public string GBFeatureSet_annotsource {
        get {
            return this.gBFeatureSet_annotsourceField;
        }
        set {
            this.gBFeatureSet_annotsourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("GBFeature", IsNullable=false)]
    public GBFeature[] GBFeatureSet_features {
        get {
            return this.gBFeatureSet_featuresField;
        }
        set {
            this.gBFeatureSet_featuresField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBAltSeqData {
    
    private string gBAltSeqData_nameField;
    
    private GBAltSeqItem[] gBAltSeqData_itemsField;
    
    /// <remarks/>
    public string GBAltSeqData_name {
        get {
            return this.gBAltSeqData_nameField;
        }
        set {
            this.gBAltSeqData_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("GBAltSeqItem", IsNullable=false)]
    public GBAltSeqItem[] GBAltSeqData_items {
        get {
            return this.gBAltSeqData_itemsField;
        }
        set {
            this.gBAltSeqData_itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBAltSeqItem {
    
    private GBAltSeqItem_interval gBAltSeqItem_intervalField;
    
    private GBAltSeqItem_isgap gBAltSeqItem_isgapField;
    
    private int gBAltSeqItem_gaplengthField;
    
    private string gBAltSeqItem_gaptypeField;
    
    private string gBAltSeqItem_gaplinkageField;
    
    private string gBAltSeqItem_gapcommentField;
    
    private string gBAltSeqItem_firstaccnField;
    
    private string gBAltSeqItem_lastaccnField;
    
    private string gBAltSeqItem_valueField;
    
    /// <remarks/>
    public GBAltSeqItem_interval GBAltSeqItem_interval {
        get {
            return this.gBAltSeqItem_intervalField;
        }
        set {
            this.gBAltSeqItem_intervalField = value;
        }
    }
    
    /// <remarks/>
    public GBAltSeqItem_isgap GBAltSeqItem_isgap {
        get {
            return this.gBAltSeqItem_isgapField;
        }
        set {
            this.gBAltSeqItem_isgapField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBAltSeqItem_gap-length")]
    public int GBAltSeqItem_gaplength {
        get {
            return this.gBAltSeqItem_gaplengthField;
        }
        set {
            this.gBAltSeqItem_gaplengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBAltSeqItem_gap-type")]
    public string GBAltSeqItem_gaptype {
        get {
            return this.gBAltSeqItem_gaptypeField;
        }
        set {
            this.gBAltSeqItem_gaptypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBAltSeqItem_gap-linkage")]
    public string GBAltSeqItem_gaplinkage {
        get {
            return this.gBAltSeqItem_gaplinkageField;
        }
        set {
            this.gBAltSeqItem_gaplinkageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBAltSeqItem_gap-comment")]
    public string GBAltSeqItem_gapcomment {
        get {
            return this.gBAltSeqItem_gapcommentField;
        }
        set {
            this.gBAltSeqItem_gapcommentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBAltSeqItem_first-accn")]
    public string GBAltSeqItem_firstaccn {
        get {
            return this.gBAltSeqItem_firstaccnField;
        }
        set {
            this.gBAltSeqItem_firstaccnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBAltSeqItem_last-accn")]
    public string GBAltSeqItem_lastaccn {
        get {
            return this.gBAltSeqItem_lastaccnField;
        }
        set {
            this.gBAltSeqItem_lastaccnField = value;
        }
    }
    
    /// <remarks/>
    public string GBAltSeqItem_value {
        get {
            return this.gBAltSeqItem_valueField;
        }
        set {
            this.gBAltSeqItem_valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBAltSeqItem_interval {
    
    private GBInterval gBIntervalField;
    
    /// <remarks/>
    public GBInterval GBInterval {
        get {
            return this.gBIntervalField;
        }
        set {
            this.gBIntervalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBAltSeqItem_isgap {
    
    private GBAltSeqItem_isgapValue valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public GBAltSeqItem_isgapValue value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
public enum GBAltSeqItem_isgapValue {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute("GBSeq_other-seqids", Namespace="", IsNullable=false)]
public partial class GBSeq_otherseqids {
    
    private string[] gBSeqidField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBSeqid")]
    public string[] GBSeqid {
        get {
            return this.gBSeqidField;
        }
        set {
            this.gBSeqidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute("GBSeq_secondary-accessions", Namespace="", IsNullable=false)]
public partial class GBSeq_secondaryaccessions {
    
    private string[] gBSecondaryaccnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBSecondary-accn")]
    public string[] GBSecondaryaccn {
        get {
            return this.gBSecondaryaccnField;
        }
        set {
            this.gBSecondaryaccnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBSeq_keywords {
    
    private string[] gBKeywordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBKeyword")]
    public string[] GBKeyword {
        get {
            return this.gBKeywordField;
        }
        set {
            this.gBKeywordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBSeq_references {
    
    private GBReference[] gBReferenceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBReference")]
    public GBReference[] GBReference {
        get {
            return this.gBReferenceField;
        }
        set {
            this.gBReferenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute("GBSeq_comment-set", Namespace="", IsNullable=false)]
public partial class GBSeq_commentset {
    
    private GBComment[] gBCommentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBComment")]
    public GBComment[] GBComment {
        get {
            return this.gBCommentField;
        }
        set {
            this.gBCommentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute("GBSeq_struc-comments", Namespace="", IsNullable=false)]
public partial class GBSeq_struccomments {
    
    private GBStrucComment[] gBStrucCommentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBStrucComment")]
    public GBStrucComment[] GBStrucComment {
        get {
            return this.gBStrucCommentField;
        }
        set {
            this.gBStrucCommentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute("GBSeq_feature-table", Namespace="", IsNullable=false)]
public partial class GBSeq_featuretable {
    
    private GBFeature[] gBFeatureField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBFeature")]
    public GBFeature[] GBFeature {
        get {
            return this.gBFeatureField;
        }
        set {
            this.gBFeatureField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute("GBSeq_feature-set", Namespace="", IsNullable=false)]
public partial class GBSeq_featureset {
    
    private GBFeatureSet[] gBFeatureSetField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBFeatureSet")]
    public GBFeatureSet[] GBFeatureSet {
        get {
            return this.gBFeatureSetField;
        }
        set {
            this.gBFeatureSetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute("GBSeq_alt-seq", Namespace="", IsNullable=false)]
public partial class GBSeq_altseq {
    
    private GBAltSeqData[] gBAltSeqDataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBAltSeqData")]
    public GBAltSeqData[] GBAltSeqData {
        get {
            return this.gBAltSeqDataField;
        }
        set {
            this.gBAltSeqDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBSeq_xrefs {
    
    private GBXref[] gBXrefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBXref")]
    public GBXref[] GBXref {
        get {
            return this.gBXrefField;
        }
        set {
            this.gBXrefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBReference_authors {
    
    private string[] gBAuthorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBAuthor")]
    public string[] GBAuthor {
        get {
            return this.gBAuthorField;
        }
        set {
            this.gBAuthorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBReference_xref {
    
    private GBXref[] gBXrefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBXref")]
    public GBXref[] GBXref {
        get {
            return this.gBXrefField;
        }
        set {
            this.gBXrefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBComment_paragraphs {
    
    private string[] gBCommentParagraphField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBCommentParagraph")]
    public string[] GBCommentParagraph {
        get {
            return this.gBCommentParagraphField;
        }
        set {
            this.gBCommentParagraphField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBStrucComment_items {
    
    private GBStrucCommentItem[] gBStrucCommentItemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBStrucCommentItem")]
    public GBStrucCommentItem[] GBStrucCommentItem {
        get {
            return this.gBStrucCommentItemField;
        }
        set {
            this.gBStrucCommentItemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBFeatureSet_features {
    
    private GBFeature[] gBFeatureField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBFeature")]
    public GBFeature[] GBFeature {
        get {
            return this.gBFeatureField;
        }
        set {
            this.gBFeatureField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBFeature_intervals {
    
    private GBInterval[] gBIntervalField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBInterval")]
    public GBInterval[] GBInterval {
        get {
            return this.gBIntervalField;
        }
        set {
            this.gBIntervalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBFeature_quals {
    
    private GBQualifier[] gBQualifierField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBQualifier")]
    public GBQualifier[] GBQualifier {
        get {
            return this.gBQualifierField;
        }
        set {
            this.gBQualifierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBFeature_xrefs {
    
    private GBXref[] gBXrefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBXref")]
    public GBXref[] GBXref {
        get {
            return this.gBXrefField;
        }
        set {
            this.gBXrefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GBAltSeqData_items {
    
    private GBAltSeqItem[] gBAltSeqItemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBAltSeqItem")]
    public GBAltSeqItem[] GBAltSeqItem {
        get {
            return this.gBAltSeqItemField;
        }
        set {
            this.gBAltSeqItemField = value;
        }
    }
}