//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8669
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace hlatools.core.DataObjects.Imgt {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hla.alleles.org/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hla.alleles.org/xml", IsNullable=false)]
    public partial class alleles {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("allele")]
        public allele[] allele;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hla.alleles.org/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hla.alleles.org/xml", IsNullable=false)]
    public partial class allele {
        
        /// <remarks/>
        public releaseversions releaseversions;
        
        /// <remarks/>
        public locus locus;
        
        /// <remarks/>
        public cwd_catalogue cwd_catalogue;
        
        /// <remarks/>
        public hla_g_group hla_g_group;
        
        /// <remarks/>
        public hla_p_group hla_p_group;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("citation", IsNullable=false)]
        public citation[] citations;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("xref", IsNullable=false)]
        public xref[] sourcexrefs;
        
        /// <remarks/>
        public sourcematerial sourcematerial;
        
        /// <remarks/>
        public sequence sequence;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string dateassigned;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hla.alleles.org/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hla.alleles.org/xml", IsNullable=false)]
    public partial class releaseversions {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string confirmed;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string currentrelease;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string firstreleased;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string lastupdated;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string releasestatus;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hla.alleles.org/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hla.alleles.org/xml", IsNullable=false)]
    public partial class locus {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string @class;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string genesystem;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string hugogenename;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string locusname;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hla.alleles.org/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hla.alleles.org/xml", IsNullable=false)]
    public partial class cwd_catalogue {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string cwd_reference;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cwd_status;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string cwd_version;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hla.alleles.org/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hla.alleles.org/xml", IsNullable=false)]
    public partial class hla_g_group {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string status;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hla.alleles.org/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hla.alleles.org/xml", IsNullable=false)]
    public partial class hla_p_group {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string status;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hla.alleles.org/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hla.alleles.org/xml", IsNullable=false)]
    public partial class citation {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string authors;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string location;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string pubmed;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hla.alleles.org/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hla.alleles.org/xml", IsNullable=false)]
    public partial class xref {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string acc;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string pid;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hla.alleles.org/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hla.alleles.org/xml", IsNullable=false)]
    public partial class sourcematerial {
        
        /// <remarks/>
        public species species;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("sample_ethnicity", IsNullable=false)]
        public string[] ethnicity;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("sample", IsNullable=false)]
        public sample[] samples;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hla.alleles.org/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hla.alleles.org/xml", IsNullable=false)]
    public partial class species {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string commonname;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string latinname;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string ncbitaxon;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hla.alleles.org/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hla.alleles.org/xml", IsNullable=false)]
    public partial class sample {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hla.alleles.org/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hla.alleles.org/xml", IsNullable=false)]
    public partial class sequence {
        
        /// <remarks/>
        public alignmentreference alignmentreference;
        
        /// <remarks/>
        public string nucsequence;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("feature")]
        public feature[] feature;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hla.alleles.org/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hla.alleles.org/xml", IsNullable=false)]
    public partial class alignmentreference {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string alleleid;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string allelename;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hla.alleles.org/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hla.alleles.org/xml", IsNullable=false)]
    public partial class feature {
        
        /// <remarks/>
        public SequenceCoordinates SequenceCoordinates;
        
        /// <remarks/>
        public cDNACoordinates cDNACoordinates;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cDNAindel", typeof(cDNAindel))]
        [System.Xml.Serialization.XmlElementAttribute("translation", typeof(string))]
        public object[] Items;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string featuretype;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string order;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string status;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hla.alleles.org/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hla.alleles.org/xml", IsNullable=false)]
    public partial class SequenceCoordinates {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string end;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string start;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hla.alleles.org/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hla.alleles.org/xml", IsNullable=false)]
    public partial class cDNACoordinates {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string end;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string readingframe;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string start;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hla.alleles.org/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hla.alleles.org/xml", IsNullable=false)]
    public partial class cDNAindel {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string end;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string expressed;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string size;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string start;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hla.alleles.org/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hla.alleles.org/xml", IsNullable=false)]
    public partial class citations {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("citation")]
        public citation[] citation;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hla.alleles.org/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hla.alleles.org/xml", IsNullable=false)]
    public partial class sourcexrefs {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("xref")]
        public xref[] xref;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hla.alleles.org/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hla.alleles.org/xml", IsNullable=false)]
    public partial class ethnicity {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sample_ethnicity")]
        public string[] sample_ethnicity;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hla.alleles.org/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hla.alleles.org/xml", IsNullable=false)]
    public partial class samples {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sample")]
        public sample[] sample;
    }
}
